### ISSUE TITLE
license

### ISSUE THREAD

**Issue by loriab** [mzott/Psi4-OpenMM-Interface#2]
Hi Mike,

Would you have time to slap a license onto this repo? Perhaps BSD-3-Clause or LGPL-3.0.

Or only if you want nothing further to do with the repo, you could transfer it to user cdsgroup. I'm not likely to be making further update requests -- the license is just to complete a table for a paper.

**Comment by mzott** [comment]
Hey Lori,

If you let me know what to do then I can do this. A bit Rusty since I've
went over to the synthetic side!

Mike

**Comment by loriab** [comment]
Thanks, Mike.

Pretty much, take a file like [this](https://raw.githubusercontent.com/MolSSI/QCElemental/master/LICENSE), edit the third line, and put it in a file called `LICENSE` at the top level of your repo. You can probably do it purely through the GitHub web interface -- no clone required.

**Comment by mzott** [comment]
Sorry it took a while but I merged the request. Thanks!

Mike

**Comment by loriab** [comment]
Perfect, thanks. Now GH recognizes the license on the front page above "Clone and Download".

There was interest from an external entity for continuing your work here. Will let you know and consult with you on any developments.

**Comment by mzott** [comment]
Cool, thanks for the update! Would be interesting to see better methods be
developed based on qmmm. Now my computational chemistry is mostly limited
to computing bond strengths in inorganic complexes but this requires an
entropy correction that is mediocre at best and has no contributions from
solvation.

Mike
